### ISSUE TITLE
Preselecting date range ...

### ISSUE THREAD

**Issue by sanzwebdevelopment** [CodyHouse/cd-date-range-changelog#1]
Hi all ... fantastic component :-)

Just wondering how I would preselect the start date and end date using JS?

Basically I have an API that returns a checkin and checkout date (formatted as YY-MM-DD) in a JSON string, and I'd like to show that those dates are selected (preselected) in the calendar (but in the DD/MM/YY format) ie the user has not used the calendar to select the dates.

Any suggestions you have would be much appreciated :-)

Thanks.

**Comment by claudia-romano** [comment]
Hi there,
you can use  the two input elements `.js-date-range__text--start` and `.js-date-range__text--end` and set their `value` equal to the dates you want to use. Make sure to use the proper date format (e.g., dd/mm/yyyy).

If your dates are retrieved after the content is rendered, you may need to dynamically initialize the date range element. More info [here](https://codyhouse.co/ds/components/info/date-range#dynamic).

Make sure to get the latest version of the component JS code (we just pushed an update):
https://codyhouse.co/ds/components/app/date-range

Cheers!

**Comment by sanzwebdevelopment** [comment]
Thanks for the reply Claudia :-)

I've successfully set both the start and end dates now thanks to your help ... the preset dates now show up as selected but only when the user clicks the "Choose date" button (.js-date-range__trigger) after which that the initial label (.js-date-range__trigger-label) is hidden and the next span has the class is-hidden removed. Is there a way to manually trigger that without showing the calendar?

I've done the following:

$('.js-date-range__text--start').val( formattedCheckin );
$('.js-date-range__value--start').val( formattedCheckin );

to add the formatted dates in, however on that button the text/value doesn't change to the dates automatically on page load if you see what I mean :-)

Thanks for the assistance.

**Comment by claudia-romano** [comment]
Hi there,
are you importing the latest version of the component? This was an issue with the previous version that has now been fixed:
https://codyhouse.co/ds/components/app/date-range

Cheers!

**Comment by sanzwebdevelopment** [comment]
Hey Claudia ... hmmm thought I was as it's a new install. I'll clear my npm cache and try again :-)

Sorry for the bother ... should have checked all that first.
